/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mostrarnombre;

import java.awt.Color;



/**
 *
 * @author Asus
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
        /*jButtonSHOW.setBackground(Color.red);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPantalla1 = new javax.swing.JPanel();
        jButtonESP = new javax.swing.JButton();
        jButtonENG = new javax.swing.JButton();
        jTextFieldNombre = new javax.swing.JTextField();
        jButtonSHOW = new javax.swing.JButton();
        jButtonRESET = new javax.swing.JButton();
        jPanelPantalla2 = new javax.swing.JPanel();
        jLabelSubTitulo = new javax.swing.JLabel();
        jLabelSubTitulo1 = new javax.swing.JLabel();
        jLabelSubTitulo2 = new javax.swing.JLabel();
        jLabelSubTitulo3 = new javax.swing.JLabel();
        jLabelSubTitulo4 = new javax.swing.JLabel();
        jLabelMostrarNombre = new javax.swing.JLabel();
        jLabelMostrarNombre1 = new javax.swing.JLabel();
        jLabelMostrarNombre2 = new javax.swing.JLabel();
        jLabelMostrarNombre3 = new javax.swing.JLabel();
        jLabelMostrarNombre4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo2 = new javax.swing.JLabel();
        jTextFieldNombre1 = new javax.swing.JTextField();
        jButtonSEARCH = new javax.swing.JButton();
        jLabelLetra = new javax.swing.JLabel();
        jButtonESP1 = new javax.swing.JButton();
        jButtonESP2 = new javax.swing.JButton();
        jLabelTitulo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPantalla1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPantalla1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButtonESP.setBackground(new java.awt.Color(0, 0, 204));
        jButtonESP.setForeground(new java.awt.Color(255, 255, 255));
        jButtonESP.setText("ESP");

        jButtonENG.setBackground(new java.awt.Color(247, 148, 0));
        jButtonENG.setForeground(new java.awt.Color(255, 255, 255));
        jButtonENG.setText("ENG");

        jTextFieldNombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jButtonSHOW.setBackground(new java.awt.Color(212, 0, 0));
        jButtonSHOW.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonSHOW.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSHOW.setText("SHOW");
        jButtonSHOW.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3)));
        jButtonSHOW.setFocusPainted(false);
        jButtonSHOW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSHOWActionPerformed(evt);
            }
        });

        jButtonRESET.setBackground(new java.awt.Color(0, 118, 0));
        jButtonRESET.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonRESET.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRESET.setText("RESET");
        jButtonRESET.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3)));

        jPanelPantalla2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPantalla2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Information", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        jLabelSubTitulo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelSubTitulo.setText("Your name is :");

        jLabelSubTitulo1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelSubTitulo1.setText("Your name in MAY :");

        jLabelSubTitulo2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelSubTitulo2.setText("Your name in MIN :");

        jLabelSubTitulo3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelSubTitulo3.setText("Total characters :");

        jLabelSubTitulo4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelSubTitulo4.setText("Initial caption letters :");

        jLabelMostrarNombre.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        jLabelMostrarNombre1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        jLabelMostrarNombre2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        jLabelMostrarNombre3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        jLabelMostrarNombre4.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Letter finder", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        jLabelTitulo2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelTitulo2.setText("Type a number:");

        jTextFieldNombre1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldNombre1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jButtonSEARCH.setBackground(new java.awt.Color(204, 255, 0));
        jButtonSEARCH.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonSEARCH.setText("SEARCH");

        jLabelLetra.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLetra.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabelLetra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLetra.setText("?");

        jButtonESP1.setBackground(new java.awt.Color(0, 0, 204));
        jButtonESP1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonESP1.setText("MAY");

        jButtonESP2.setBackground(new java.awt.Color(255, 153, 0));
        jButtonESP2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonESP2.setText("MIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldNombre1)
                    .addComponent(jLabelTitulo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSEARCH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(76, 76, 76)
                .addComponent(jLabelLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonESP1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(jButtonESP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTitulo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jButtonSEARCH)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonESP1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonESP2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabelLetra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanelPantalla2Layout = new javax.swing.GroupLayout(jPanelPantalla2);
        jPanelPantalla2.setLayout(jPanelPantalla2Layout);
        jPanelPantalla2Layout.setHorizontalGroup(
            jPanelPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPantalla2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPantalla2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanelPantalla2Layout.createSequentialGroup()
                        .addGroup(jPanelPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelPantalla2Layout.createSequentialGroup()
                                .addComponent(jLabelSubTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jLabelMostrarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelPantalla2Layout.createSequentialGroup()
                                .addGroup(jPanelPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSubTitulo1)
                                    .addComponent(jLabelSubTitulo2)
                                    .addComponent(jLabelSubTitulo3)
                                    .addComponent(jLabelSubTitulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelMostrarNombre1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                                    .addComponent(jLabelMostrarNombre3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelMostrarNombre4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelMostrarNombre2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelPantalla2Layout.setVerticalGroup(
            jPanelPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPantalla2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelSubTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMostrarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelMostrarNombre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSubTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(jPanelPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSubTitulo2)
                    .addComponent(jLabelMostrarNombre3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPantalla2Layout.createSequentialGroup()
                        .addComponent(jLabelSubTitulo3)
                        .addGap(3, 3, 3))
                    .addComponent(jLabelMostrarNombre4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSubTitulo4)
                    .addComponent(jLabelMostrarNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabelTitulo1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelTitulo1.setText("Your name:");

        javax.swing.GroupLayout jPanelPantalla1Layout = new javax.swing.GroupLayout(jPanelPantalla1);
        jPanelPantalla1.setLayout(jPanelPantalla1Layout);
        jPanelPantalla1Layout.setHorizontalGroup(
            jPanelPantalla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPantalla1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPantalla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPantalla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelPantalla1Layout.createSequentialGroup()
                            .addComponent(jLabelTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonESP)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonENG)))
                    .addGroup(jPanelPantalla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonSHOW, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRESET, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelPantalla2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPantalla1Layout.setVerticalGroup(
            jPanelPantalla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPantalla1Layout.createSequentialGroup()
                .addGroup(jPanelPantalla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPantalla1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabelTitulo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPantalla1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelPantalla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonESP)
                            .addComponent(jButtonENG))
                        .addGap(26, 26, 26)))
                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSHOW)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRESET)
                .addGap(18, 18, 18)
                .addComponent(jPanelPantalla2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPantalla1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPantalla1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSHOWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSHOWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSHOWActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonENG;
    private javax.swing.JButton jButtonESP;
    private javax.swing.JButton jButtonESP1;
    private javax.swing.JButton jButtonESP2;
    private javax.swing.JButton jButtonRESET;
    private javax.swing.JButton jButtonSEARCH;
    private javax.swing.JButton jButtonSHOW;
    private javax.swing.JLabel jLabelLetra;
    private javax.swing.JLabel jLabelMostrarNombre;
    private javax.swing.JLabel jLabelMostrarNombre1;
    private javax.swing.JLabel jLabelMostrarNombre2;
    private javax.swing.JLabel jLabelMostrarNombre3;
    private javax.swing.JLabel jLabelMostrarNombre4;
    private javax.swing.JLabel jLabelSubTitulo;
    private javax.swing.JLabel jLabelSubTitulo1;
    private javax.swing.JLabel jLabelSubTitulo2;
    private javax.swing.JLabel jLabelSubTitulo3;
    private javax.swing.JLabel jLabelSubTitulo4;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelPantalla1;
    private javax.swing.JPanel jPanelPantalla2;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombre1;
    // End of variables declaration//GEN-END:variables
}
